//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_SOA_BN.MyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfCountry", Namespace="http://tempuri.org/", ItemName="country")]
    [System.SerializableAttribute()]
    public class ArrayOfCountry : System.Collections.Generic.List<Client_SOA_BN.MyService.country> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="country", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContinentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionField;
        
        private decimal SurfaceAreaField;
        
        private System.Nullable<short> IndepYearField;
        
        private int PopulationField;
        
        private System.Nullable<decimal> LifeExpectancyField;
        
        private System.Nullable<decimal> GNPField;
        
        private System.Nullable<decimal> GNPOldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GovernmentFormField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeadOfStateField;
        
        private System.Nullable<int> CapitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Code2Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Continent {
            get {
                return this.ContinentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContinentField, value) != true)) {
                    this.ContinentField = value;
                    this.RaisePropertyChanged("Continent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Region {
            get {
                return this.RegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionField, value) != true)) {
                    this.RegionField = value;
                    this.RaisePropertyChanged("Region");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal SurfaceArea {
            get {
                return this.SurfaceAreaField;
            }
            set {
                if ((this.SurfaceAreaField.Equals(value) != true)) {
                    this.SurfaceAreaField = value;
                    this.RaisePropertyChanged("SurfaceArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<short> IndepYear {
            get {
                return this.IndepYearField;
            }
            set {
                if ((this.IndepYearField.Equals(value) != true)) {
                    this.IndepYearField = value;
                    this.RaisePropertyChanged("IndepYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int Population {
            get {
                return this.PopulationField;
            }
            set {
                if ((this.PopulationField.Equals(value) != true)) {
                    this.PopulationField = value;
                    this.RaisePropertyChanged("Population");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<decimal> LifeExpectancy {
            get {
                return this.LifeExpectancyField;
            }
            set {
                if ((this.LifeExpectancyField.Equals(value) != true)) {
                    this.LifeExpectancyField = value;
                    this.RaisePropertyChanged("LifeExpectancy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<decimal> GNP {
            get {
                return this.GNPField;
            }
            set {
                if ((this.GNPField.Equals(value) != true)) {
                    this.GNPField = value;
                    this.RaisePropertyChanged("GNP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<decimal> GNPOld {
            get {
                return this.GNPOldField;
            }
            set {
                if ((this.GNPOldField.Equals(value) != true)) {
                    this.GNPOldField = value;
                    this.RaisePropertyChanged("GNPOld");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string LocalName {
            get {
                return this.LocalNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalNameField, value) != true)) {
                    this.LocalNameField = value;
                    this.RaisePropertyChanged("LocalName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string GovernmentForm {
            get {
                return this.GovernmentFormField;
            }
            set {
                if ((object.ReferenceEquals(this.GovernmentFormField, value) != true)) {
                    this.GovernmentFormField = value;
                    this.RaisePropertyChanged("GovernmentForm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string HeadOfState {
            get {
                return this.HeadOfStateField;
            }
            set {
                if ((object.ReferenceEquals(this.HeadOfStateField, value) != true)) {
                    this.HeadOfStateField = value;
                    this.RaisePropertyChanged("HeadOfState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public System.Nullable<int> Capital {
            get {
                return this.CapitalField;
            }
            set {
                if ((this.CapitalField.Equals(value) != true)) {
                    this.CapitalField = value;
                    this.RaisePropertyChanged("Capital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string Code2 {
            get {
                return this.Code2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Code2Field, value) != true)) {
                    this.Code2Field = value;
                    this.RaisePropertyChanged("Code2");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfCity", Namespace="http://tempuri.org/", ItemName="city")]
    [System.SerializableAttribute()]
    public class ArrayOfCity : System.Collections.Generic.List<Client_SOA_BN.MyService.city> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="city", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class city : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistrictField;
        
        private int PopulationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string District {
            get {
                return this.DistrictField;
            }
            set {
                if ((object.ReferenceEquals(this.DistrictField, value) != true)) {
                    this.DistrictField = value;
                    this.RaisePropertyChanged("District");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Population {
            get {
                return this.PopulationField;
            }
            set {
                if ((this.PopulationField.Equals(value) != true)) {
                    this.PopulationField = value;
                    this.RaisePropertyChanged("Population");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyService.ServerRefSoap")]
    public interface ServerRefSoap {
        
        // CODEGEN: Generating message contract since element name GreetWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GreetWorld", ReplyAction="*")]
        Client_SOA_BN.MyService.GreetWorldResponse GreetWorld(Client_SOA_BN.MyService.GreetWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GreetWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Client_SOA_BN.MyService.GreetWorldResponse> GreetWorldAsync(Client_SOA_BN.MyService.GreetWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetCountriesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountries", ReplyAction="*")]
        Client_SOA_BN.MyService.GetCountriesResponse GetCountries(Client_SOA_BN.MyService.GetCountriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountries", ReplyAction="*")]
        System.Threading.Tasks.Task<Client_SOA_BN.MyService.GetCountriesResponse> GetCountriesAsync(Client_SOA_BN.MyService.GetCountriesRequest request);
        
        // CODEGEN: Generating message contract since element name code from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountryByCode", ReplyAction="*")]
        Client_SOA_BN.MyService.GetCountryByCodeResponse GetCountryByCode(Client_SOA_BN.MyService.GetCountryByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountryByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<Client_SOA_BN.MyService.GetCountryByCodeResponse> GetCountryByCodeAsync(Client_SOA_BN.MyService.GetCountryByCodeRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCitiesByName", ReplyAction="*")]
        Client_SOA_BN.MyService.GetCitiesByNameResponse GetCitiesByName(Client_SOA_BN.MyService.GetCitiesByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCitiesByName", ReplyAction="*")]
        System.Threading.Tasks.Task<Client_SOA_BN.MyService.GetCitiesByNameResponse> GetCitiesByNameAsync(Client_SOA_BN.MyService.GetCitiesByNameRequest request);
        
        // CODEGEN: Generating message contract since element name countryName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCitiesByCountry", ReplyAction="*")]
        Client_SOA_BN.MyService.GetCitiesByCountryResponse GetCitiesByCountry(Client_SOA_BN.MyService.GetCitiesByCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCitiesByCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<Client_SOA_BN.MyService.GetCitiesByCountryResponse> GetCitiesByCountryAsync(Client_SOA_BN.MyService.GetCitiesByCountryRequest request);
        
        // CODEGEN: Generating message contract since element name countryName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PopulationOfCountry", ReplyAction="*")]
        Client_SOA_BN.MyService.PopulationOfCountryResponse PopulationOfCountry(Client_SOA_BN.MyService.PopulationOfCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PopulationOfCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<Client_SOA_BN.MyService.PopulationOfCountryResponse> PopulationOfCountryAsync(Client_SOA_BN.MyService.PopulationOfCountryRequest request);
        
        // CODEGEN: Generating message contract since element name GetCityByPopulationResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCityByPopulation", ReplyAction="*")]
        Client_SOA_BN.MyService.GetCityByPopulationResponse GetCityByPopulation(Client_SOA_BN.MyService.GetCityByPopulationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCityByPopulation", ReplyAction="*")]
        System.Threading.Tasks.Task<Client_SOA_BN.MyService.GetCityByPopulationResponse> GetCityByPopulationAsync(Client_SOA_BN.MyService.GetCityByPopulationRequest request);
        
        // CODEGEN: Generating message contract since element name countryCode from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OfficialLanguagesOfCountries", ReplyAction="*")]
        Client_SOA_BN.MyService.OfficialLanguagesOfCountriesResponse OfficialLanguagesOfCountries(Client_SOA_BN.MyService.OfficialLanguagesOfCountriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OfficialLanguagesOfCountries", ReplyAction="*")]
        System.Threading.Tasks.Task<Client_SOA_BN.MyService.OfficialLanguagesOfCountriesResponse> OfficialLanguagesOfCountriesAsync(Client_SOA_BN.MyService.OfficialLanguagesOfCountriesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GreetWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GreetWorld", Namespace="http://tempuri.org/", Order=0)]
        public Client_SOA_BN.MyService.GreetWorldRequestBody Body;
        
        public GreetWorldRequest() {
        }
        
        public GreetWorldRequest(Client_SOA_BN.MyService.GreetWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GreetWorldRequestBody {
        
        public GreetWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GreetWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GreetWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client_SOA_BN.MyService.GreetWorldResponseBody Body;
        
        public GreetWorldResponse() {
        }
        
        public GreetWorldResponse(Client_SOA_BN.MyService.GreetWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GreetWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GreetWorldResult;
        
        public GreetWorldResponseBody() {
        }
        
        public GreetWorldResponseBody(string GreetWorldResult) {
            this.GreetWorldResult = GreetWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountries", Namespace="http://tempuri.org/", Order=0)]
        public Client_SOA_BN.MyService.GetCountriesRequestBody Body;
        
        public GetCountriesRequest() {
        }
        
        public GetCountriesRequest(Client_SOA_BN.MyService.GetCountriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCountriesRequestBody {
        
        public GetCountriesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client_SOA_BN.MyService.GetCountriesResponseBody Body;
        
        public GetCountriesResponse() {
        }
        
        public GetCountriesResponse(Client_SOA_BN.MyService.GetCountriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client_SOA_BN.MyService.ArrayOfCountry GetCountriesResult;
        
        public GetCountriesResponseBody() {
        }
        
        public GetCountriesResponseBody(Client_SOA_BN.MyService.ArrayOfCountry GetCountriesResult) {
            this.GetCountriesResult = GetCountriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountryByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryByCode", Namespace="http://tempuri.org/", Order=0)]
        public Client_SOA_BN.MyService.GetCountryByCodeRequestBody Body;
        
        public GetCountryByCodeRequest() {
        }
        
        public GetCountryByCodeRequest(Client_SOA_BN.MyService.GetCountryByCodeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountryByCodeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string code;
        
        public GetCountryByCodeRequestBody() {
        }
        
        public GetCountryByCodeRequestBody(string code) {
            this.code = code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountryByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryByCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client_SOA_BN.MyService.GetCountryByCodeResponseBody Body;
        
        public GetCountryByCodeResponse() {
        }
        
        public GetCountryByCodeResponse(Client_SOA_BN.MyService.GetCountryByCodeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountryByCodeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client_SOA_BN.MyService.ArrayOfCountry GetCountryByCodeResult;
        
        public GetCountryByCodeResponseBody() {
        }
        
        public GetCountryByCodeResponseBody(Client_SOA_BN.MyService.ArrayOfCountry GetCountryByCodeResult) {
            this.GetCountryByCodeResult = GetCountryByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCitiesByName", Namespace="http://tempuri.org/", Order=0)]
        public Client_SOA_BN.MyService.GetCitiesByNameRequestBody Body;
        
        public GetCitiesByNameRequest() {
        }
        
        public GetCitiesByNameRequest(Client_SOA_BN.MyService.GetCitiesByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCitiesByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetCitiesByNameRequestBody() {
        }
        
        public GetCitiesByNameRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCitiesByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client_SOA_BN.MyService.GetCitiesByNameResponseBody Body;
        
        public GetCitiesByNameResponse() {
        }
        
        public GetCitiesByNameResponse(Client_SOA_BN.MyService.GetCitiesByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCitiesByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client_SOA_BN.MyService.ArrayOfCity GetCitiesByNameResult;
        
        public GetCitiesByNameResponseBody() {
        }
        
        public GetCitiesByNameResponseBody(Client_SOA_BN.MyService.ArrayOfCity GetCitiesByNameResult) {
            this.GetCitiesByNameResult = GetCitiesByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesByCountryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCitiesByCountry", Namespace="http://tempuri.org/", Order=0)]
        public Client_SOA_BN.MyService.GetCitiesByCountryRequestBody Body;
        
        public GetCitiesByCountryRequest() {
        }
        
        public GetCitiesByCountryRequest(Client_SOA_BN.MyService.GetCitiesByCountryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCitiesByCountryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string countryName;
        
        public GetCitiesByCountryRequestBody() {
        }
        
        public GetCitiesByCountryRequestBody(string countryName) {
            this.countryName = countryName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesByCountryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCitiesByCountryResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client_SOA_BN.MyService.GetCitiesByCountryResponseBody Body;
        
        public GetCitiesByCountryResponse() {
        }
        
        public GetCitiesByCountryResponse(Client_SOA_BN.MyService.GetCitiesByCountryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCitiesByCountryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client_SOA_BN.MyService.ArrayOfCity GetCitiesByCountryResult;
        
        public GetCitiesByCountryResponseBody() {
        }
        
        public GetCitiesByCountryResponseBody(Client_SOA_BN.MyService.ArrayOfCity GetCitiesByCountryResult) {
            this.GetCitiesByCountryResult = GetCitiesByCountryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PopulationOfCountryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PopulationOfCountry", Namespace="http://tempuri.org/", Order=0)]
        public Client_SOA_BN.MyService.PopulationOfCountryRequestBody Body;
        
        public PopulationOfCountryRequest() {
        }
        
        public PopulationOfCountryRequest(Client_SOA_BN.MyService.PopulationOfCountryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PopulationOfCountryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string countryName;
        
        public PopulationOfCountryRequestBody() {
        }
        
        public PopulationOfCountryRequestBody(string countryName) {
            this.countryName = countryName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PopulationOfCountryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PopulationOfCountryResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client_SOA_BN.MyService.PopulationOfCountryResponseBody Body;
        
        public PopulationOfCountryResponse() {
        }
        
        public PopulationOfCountryResponse(Client_SOA_BN.MyService.PopulationOfCountryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PopulationOfCountryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long PopulationOfCountryResult;
        
        public PopulationOfCountryResponseBody() {
        }
        
        public PopulationOfCountryResponseBody(long PopulationOfCountryResult) {
            this.PopulationOfCountryResult = PopulationOfCountryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityByPopulationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityByPopulation", Namespace="http://tempuri.org/", Order=0)]
        public Client_SOA_BN.MyService.GetCityByPopulationRequestBody Body;
        
        public GetCityByPopulationRequest() {
        }
        
        public GetCityByPopulationRequest(Client_SOA_BN.MyService.GetCityByPopulationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCityByPopulationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int minPopulation;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int maxPopulation;
        
        public GetCityByPopulationRequestBody() {
        }
        
        public GetCityByPopulationRequestBody(int minPopulation, int maxPopulation) {
            this.minPopulation = minPopulation;
            this.maxPopulation = maxPopulation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityByPopulationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityByPopulationResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client_SOA_BN.MyService.GetCityByPopulationResponseBody Body;
        
        public GetCityByPopulationResponse() {
        }
        
        public GetCityByPopulationResponse(Client_SOA_BN.MyService.GetCityByPopulationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCityByPopulationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client_SOA_BN.MyService.ArrayOfCity GetCityByPopulationResult;
        
        public GetCityByPopulationResponseBody() {
        }
        
        public GetCityByPopulationResponseBody(Client_SOA_BN.MyService.ArrayOfCity GetCityByPopulationResult) {
            this.GetCityByPopulationResult = GetCityByPopulationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OfficialLanguagesOfCountriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OfficialLanguagesOfCountries", Namespace="http://tempuri.org/", Order=0)]
        public Client_SOA_BN.MyService.OfficialLanguagesOfCountriesRequestBody Body;
        
        public OfficialLanguagesOfCountriesRequest() {
        }
        
        public OfficialLanguagesOfCountriesRequest(Client_SOA_BN.MyService.OfficialLanguagesOfCountriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OfficialLanguagesOfCountriesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string countryCode;
        
        public OfficialLanguagesOfCountriesRequestBody() {
        }
        
        public OfficialLanguagesOfCountriesRequestBody(string countryCode) {
            this.countryCode = countryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OfficialLanguagesOfCountriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OfficialLanguagesOfCountriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client_SOA_BN.MyService.OfficialLanguagesOfCountriesResponseBody Body;
        
        public OfficialLanguagesOfCountriesResponse() {
        }
        
        public OfficialLanguagesOfCountriesResponse(Client_SOA_BN.MyService.OfficialLanguagesOfCountriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OfficialLanguagesOfCountriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client_SOA_BN.MyService.ArrayOfString OfficialLanguagesOfCountriesResult;
        
        public OfficialLanguagesOfCountriesResponseBody() {
        }
        
        public OfficialLanguagesOfCountriesResponseBody(Client_SOA_BN.MyService.ArrayOfString OfficialLanguagesOfCountriesResult) {
            this.OfficialLanguagesOfCountriesResult = OfficialLanguagesOfCountriesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServerRefSoapChannel : Client_SOA_BN.MyService.ServerRefSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServerRefSoapClient : System.ServiceModel.ClientBase<Client_SOA_BN.MyService.ServerRefSoap>, Client_SOA_BN.MyService.ServerRefSoap {
        
        public ServerRefSoapClient() {
        }
        
        public ServerRefSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServerRefSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerRefSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServerRefSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_SOA_BN.MyService.GreetWorldResponse Client_SOA_BN.MyService.ServerRefSoap.GreetWorld(Client_SOA_BN.MyService.GreetWorldRequest request) {
            return base.Channel.GreetWorld(request);
        }
        
        public string GreetWorld() {
            Client_SOA_BN.MyService.GreetWorldRequest inValue = new Client_SOA_BN.MyService.GreetWorldRequest();
            inValue.Body = new Client_SOA_BN.MyService.GreetWorldRequestBody();
            Client_SOA_BN.MyService.GreetWorldResponse retVal = ((Client_SOA_BN.MyService.ServerRefSoap)(this)).GreetWorld(inValue);
            return retVal.Body.GreetWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client_SOA_BN.MyService.GreetWorldResponse> Client_SOA_BN.MyService.ServerRefSoap.GreetWorldAsync(Client_SOA_BN.MyService.GreetWorldRequest request) {
            return base.Channel.GreetWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client_SOA_BN.MyService.GreetWorldResponse> GreetWorldAsync() {
            Client_SOA_BN.MyService.GreetWorldRequest inValue = new Client_SOA_BN.MyService.GreetWorldRequest();
            inValue.Body = new Client_SOA_BN.MyService.GreetWorldRequestBody();
            return ((Client_SOA_BN.MyService.ServerRefSoap)(this)).GreetWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_SOA_BN.MyService.GetCountriesResponse Client_SOA_BN.MyService.ServerRefSoap.GetCountries(Client_SOA_BN.MyService.GetCountriesRequest request) {
            return base.Channel.GetCountries(request);
        }
        
        public Client_SOA_BN.MyService.ArrayOfCountry GetCountries() {
            Client_SOA_BN.MyService.GetCountriesRequest inValue = new Client_SOA_BN.MyService.GetCountriesRequest();
            inValue.Body = new Client_SOA_BN.MyService.GetCountriesRequestBody();
            Client_SOA_BN.MyService.GetCountriesResponse retVal = ((Client_SOA_BN.MyService.ServerRefSoap)(this)).GetCountries(inValue);
            return retVal.Body.GetCountriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client_SOA_BN.MyService.GetCountriesResponse> Client_SOA_BN.MyService.ServerRefSoap.GetCountriesAsync(Client_SOA_BN.MyService.GetCountriesRequest request) {
            return base.Channel.GetCountriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client_SOA_BN.MyService.GetCountriesResponse> GetCountriesAsync() {
            Client_SOA_BN.MyService.GetCountriesRequest inValue = new Client_SOA_BN.MyService.GetCountriesRequest();
            inValue.Body = new Client_SOA_BN.MyService.GetCountriesRequestBody();
            return ((Client_SOA_BN.MyService.ServerRefSoap)(this)).GetCountriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_SOA_BN.MyService.GetCountryByCodeResponse Client_SOA_BN.MyService.ServerRefSoap.GetCountryByCode(Client_SOA_BN.MyService.GetCountryByCodeRequest request) {
            return base.Channel.GetCountryByCode(request);
        }
        
        public Client_SOA_BN.MyService.ArrayOfCountry GetCountryByCode(string code) {
            Client_SOA_BN.MyService.GetCountryByCodeRequest inValue = new Client_SOA_BN.MyService.GetCountryByCodeRequest();
            inValue.Body = new Client_SOA_BN.MyService.GetCountryByCodeRequestBody();
            inValue.Body.code = code;
            Client_SOA_BN.MyService.GetCountryByCodeResponse retVal = ((Client_SOA_BN.MyService.ServerRefSoap)(this)).GetCountryByCode(inValue);
            return retVal.Body.GetCountryByCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client_SOA_BN.MyService.GetCountryByCodeResponse> Client_SOA_BN.MyService.ServerRefSoap.GetCountryByCodeAsync(Client_SOA_BN.MyService.GetCountryByCodeRequest request) {
            return base.Channel.GetCountryByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client_SOA_BN.MyService.GetCountryByCodeResponse> GetCountryByCodeAsync(string code) {
            Client_SOA_BN.MyService.GetCountryByCodeRequest inValue = new Client_SOA_BN.MyService.GetCountryByCodeRequest();
            inValue.Body = new Client_SOA_BN.MyService.GetCountryByCodeRequestBody();
            inValue.Body.code = code;
            return ((Client_SOA_BN.MyService.ServerRefSoap)(this)).GetCountryByCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_SOA_BN.MyService.GetCitiesByNameResponse Client_SOA_BN.MyService.ServerRefSoap.GetCitiesByName(Client_SOA_BN.MyService.GetCitiesByNameRequest request) {
            return base.Channel.GetCitiesByName(request);
        }
        
        public Client_SOA_BN.MyService.ArrayOfCity GetCitiesByName(string name) {
            Client_SOA_BN.MyService.GetCitiesByNameRequest inValue = new Client_SOA_BN.MyService.GetCitiesByNameRequest();
            inValue.Body = new Client_SOA_BN.MyService.GetCitiesByNameRequestBody();
            inValue.Body.name = name;
            Client_SOA_BN.MyService.GetCitiesByNameResponse retVal = ((Client_SOA_BN.MyService.ServerRefSoap)(this)).GetCitiesByName(inValue);
            return retVal.Body.GetCitiesByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client_SOA_BN.MyService.GetCitiesByNameResponse> Client_SOA_BN.MyService.ServerRefSoap.GetCitiesByNameAsync(Client_SOA_BN.MyService.GetCitiesByNameRequest request) {
            return base.Channel.GetCitiesByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client_SOA_BN.MyService.GetCitiesByNameResponse> GetCitiesByNameAsync(string name) {
            Client_SOA_BN.MyService.GetCitiesByNameRequest inValue = new Client_SOA_BN.MyService.GetCitiesByNameRequest();
            inValue.Body = new Client_SOA_BN.MyService.GetCitiesByNameRequestBody();
            inValue.Body.name = name;
            return ((Client_SOA_BN.MyService.ServerRefSoap)(this)).GetCitiesByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_SOA_BN.MyService.GetCitiesByCountryResponse Client_SOA_BN.MyService.ServerRefSoap.GetCitiesByCountry(Client_SOA_BN.MyService.GetCitiesByCountryRequest request) {
            return base.Channel.GetCitiesByCountry(request);
        }
        
        public Client_SOA_BN.MyService.ArrayOfCity GetCitiesByCountry(string countryName) {
            Client_SOA_BN.MyService.GetCitiesByCountryRequest inValue = new Client_SOA_BN.MyService.GetCitiesByCountryRequest();
            inValue.Body = new Client_SOA_BN.MyService.GetCitiesByCountryRequestBody();
            inValue.Body.countryName = countryName;
            Client_SOA_BN.MyService.GetCitiesByCountryResponse retVal = ((Client_SOA_BN.MyService.ServerRefSoap)(this)).GetCitiesByCountry(inValue);
            return retVal.Body.GetCitiesByCountryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client_SOA_BN.MyService.GetCitiesByCountryResponse> Client_SOA_BN.MyService.ServerRefSoap.GetCitiesByCountryAsync(Client_SOA_BN.MyService.GetCitiesByCountryRequest request) {
            return base.Channel.GetCitiesByCountryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client_SOA_BN.MyService.GetCitiesByCountryResponse> GetCitiesByCountryAsync(string countryName) {
            Client_SOA_BN.MyService.GetCitiesByCountryRequest inValue = new Client_SOA_BN.MyService.GetCitiesByCountryRequest();
            inValue.Body = new Client_SOA_BN.MyService.GetCitiesByCountryRequestBody();
            inValue.Body.countryName = countryName;
            return ((Client_SOA_BN.MyService.ServerRefSoap)(this)).GetCitiesByCountryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_SOA_BN.MyService.PopulationOfCountryResponse Client_SOA_BN.MyService.ServerRefSoap.PopulationOfCountry(Client_SOA_BN.MyService.PopulationOfCountryRequest request) {
            return base.Channel.PopulationOfCountry(request);
        }
        
        public long PopulationOfCountry(string countryName) {
            Client_SOA_BN.MyService.PopulationOfCountryRequest inValue = new Client_SOA_BN.MyService.PopulationOfCountryRequest();
            inValue.Body = new Client_SOA_BN.MyService.PopulationOfCountryRequestBody();
            inValue.Body.countryName = countryName;
            Client_SOA_BN.MyService.PopulationOfCountryResponse retVal = ((Client_SOA_BN.MyService.ServerRefSoap)(this)).PopulationOfCountry(inValue);
            return retVal.Body.PopulationOfCountryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client_SOA_BN.MyService.PopulationOfCountryResponse> Client_SOA_BN.MyService.ServerRefSoap.PopulationOfCountryAsync(Client_SOA_BN.MyService.PopulationOfCountryRequest request) {
            return base.Channel.PopulationOfCountryAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client_SOA_BN.MyService.PopulationOfCountryResponse> PopulationOfCountryAsync(string countryName) {
            Client_SOA_BN.MyService.PopulationOfCountryRequest inValue = new Client_SOA_BN.MyService.PopulationOfCountryRequest();
            inValue.Body = new Client_SOA_BN.MyService.PopulationOfCountryRequestBody();
            inValue.Body.countryName = countryName;
            return ((Client_SOA_BN.MyService.ServerRefSoap)(this)).PopulationOfCountryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_SOA_BN.MyService.GetCityByPopulationResponse Client_SOA_BN.MyService.ServerRefSoap.GetCityByPopulation(Client_SOA_BN.MyService.GetCityByPopulationRequest request) {
            return base.Channel.GetCityByPopulation(request);
        }
        
        public Client_SOA_BN.MyService.ArrayOfCity GetCityByPopulation(int minPopulation, int maxPopulation) {
            Client_SOA_BN.MyService.GetCityByPopulationRequest inValue = new Client_SOA_BN.MyService.GetCityByPopulationRequest();
            inValue.Body = new Client_SOA_BN.MyService.GetCityByPopulationRequestBody();
            inValue.Body.minPopulation = minPopulation;
            inValue.Body.maxPopulation = maxPopulation;
            Client_SOA_BN.MyService.GetCityByPopulationResponse retVal = ((Client_SOA_BN.MyService.ServerRefSoap)(this)).GetCityByPopulation(inValue);
            return retVal.Body.GetCityByPopulationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client_SOA_BN.MyService.GetCityByPopulationResponse> Client_SOA_BN.MyService.ServerRefSoap.GetCityByPopulationAsync(Client_SOA_BN.MyService.GetCityByPopulationRequest request) {
            return base.Channel.GetCityByPopulationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client_SOA_BN.MyService.GetCityByPopulationResponse> GetCityByPopulationAsync(int minPopulation, int maxPopulation) {
            Client_SOA_BN.MyService.GetCityByPopulationRequest inValue = new Client_SOA_BN.MyService.GetCityByPopulationRequest();
            inValue.Body = new Client_SOA_BN.MyService.GetCityByPopulationRequestBody();
            inValue.Body.minPopulation = minPopulation;
            inValue.Body.maxPopulation = maxPopulation;
            return ((Client_SOA_BN.MyService.ServerRefSoap)(this)).GetCityByPopulationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client_SOA_BN.MyService.OfficialLanguagesOfCountriesResponse Client_SOA_BN.MyService.ServerRefSoap.OfficialLanguagesOfCountries(Client_SOA_BN.MyService.OfficialLanguagesOfCountriesRequest request) {
            return base.Channel.OfficialLanguagesOfCountries(request);
        }
        
        public Client_SOA_BN.MyService.ArrayOfString OfficialLanguagesOfCountries(string countryCode) {
            Client_SOA_BN.MyService.OfficialLanguagesOfCountriesRequest inValue = new Client_SOA_BN.MyService.OfficialLanguagesOfCountriesRequest();
            inValue.Body = new Client_SOA_BN.MyService.OfficialLanguagesOfCountriesRequestBody();
            inValue.Body.countryCode = countryCode;
            Client_SOA_BN.MyService.OfficialLanguagesOfCountriesResponse retVal = ((Client_SOA_BN.MyService.ServerRefSoap)(this)).OfficialLanguagesOfCountries(inValue);
            return retVal.Body.OfficialLanguagesOfCountriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client_SOA_BN.MyService.OfficialLanguagesOfCountriesResponse> Client_SOA_BN.MyService.ServerRefSoap.OfficialLanguagesOfCountriesAsync(Client_SOA_BN.MyService.OfficialLanguagesOfCountriesRequest request) {
            return base.Channel.OfficialLanguagesOfCountriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client_SOA_BN.MyService.OfficialLanguagesOfCountriesResponse> OfficialLanguagesOfCountriesAsync(string countryCode) {
            Client_SOA_BN.MyService.OfficialLanguagesOfCountriesRequest inValue = new Client_SOA_BN.MyService.OfficialLanguagesOfCountriesRequest();
            inValue.Body = new Client_SOA_BN.MyService.OfficialLanguagesOfCountriesRequestBody();
            inValue.Body.countryCode = countryCode;
            return ((Client_SOA_BN.MyService.ServerRefSoap)(this)).OfficialLanguagesOfCountriesAsync(inValue);
        }
    }
}
